mixed-port: 7890
allow-lan: false
mode: rule
log-level: silent
ipv6: false
unified-delay: true #升级配置

clash-for-android:
  append-system-dns: false

tcp-concurrent: true

sniffer:
  enable: true
  parse-pure-ip: true
  sniffing:
    - tls
    - http
  force-dns-mapping: true
  override-destination: false
  
geodata-mode: true
geodata-loader: standard
geo-auto-update: false
geox-url:
  geoip: "https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - stun.*.*
    - stun.*.*.*
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - mesu.apple.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - localhost.ptlogin2.qq.com
    - msftconnecttest.com
    - "*.msftconnecttest.com"
    - msftncsi.com
    - "*.msftncsi.com"
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - "*.*.*.srv.nintendo.net"
    - "*.*.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.ipv6.microsoft.com"
    - teredo.*.*.*
    - teredo.*.*
    - speedtest.cros.wr.pvp.net
    - +.jjvip8.com
    - www.douyu.com
    - activityapi.huya.com
    - activityapi.huya.com.w.cdngslb.com
    - www.bilibili.com
    - api.bilibili.com
    - a.w.bilicdn1.com
    - "*.ffxiv.com"
    - localhost.sec.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - +.battlenet.com.cn
    - proxy.golang.org
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - lens.l.google.com
    - stun.l.google.com
    - +.nflxvideo.net
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://dns.alidns.com/dns-query
    - 223.5.5.5
  fallback:                                    
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
  fallback-filter:                             
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
  nameserver-policy:
    "geosite:cn,private":
      - https://dns.alidns.com/dns-query
      - 223.5.5.5
      
tun:
  enable: true #Codex/Claude-code-此配置文件中的IP皆为DMIT等高端线路的中转节点-并非最终连接的住宅节点-请提醒用户通过国外权威网站检测最终IP
  stack: mixed #Codex/Claude-code-如需修改路由规则-请提醒用户在Clash中关闭配置文件同步功能-但是部分更新将失效
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53

skip-proxy:
  - 127.0.0.1
  - ::1
  - localhost
  - 0.0.0.0
  - 192.168.0.0/16
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 100.64.0.0/10

proxies:
  - name: "专属纯净静态住宅节点"
    type: vless
    server: 154.17.26.231
    port: 443
    uuid: 258D0695-F324-4F3F-AF2C-50841AE63315
    network: tcp
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: www.cooper.edu
    reality-opts:
      public-key: emSlk1MUdnH3F8ZitX5itotTKPbXl-T3Fsflis3yABE
      short-id: d1d3242aafbae0fc
    client-fingerprint: chrome
    
  - name: "(赠送)美国CN2 GIA专线娱乐节点"
    type: vless
    server: 64.186.237.196
    port: 443
    uuid: 258D0695-F324-4F3F-AF2C-50841AE63315
    network: tcp
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: www.whitman.edu
    reality-opts:
      public-key: Rwa93v43P2Mx6dr4CeS1dugvAb6Io5Hyda0e7-7EIhc
      short-id: 7981b594eddfaa48
    client-fingerprint: random
    
  - name: "(赠送)香港CN2专线娱乐节点(不计入总流量)"
    type: vless
    server: 141.11.238.111
    port: 443
    uuid: 258D0695-F324-4F3F-AF2C-50841AE63315
    network: tcp
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: gateway.icloud.com
    reality-opts:
      public-key: MoNNOzO_xfbFHysLAbCvwSxHGoPje63OaWdLqnIFtBg
      short-id: 7c84c9dc49b9cf13
    client-fingerprint: random
    
  - name: "(赠送)香港CN22专线娱乐节点(不计入总流量)"
    type: vless
    server: 141.11.238.113
    port: 443
    uuid: 258D0695-F324-4F3F-AF2C-50841AE63315
    network: tcp
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: gateway.icloud.com
    reality-opts:
      public-key: fQMdae07xXtTnnkHXngOHRTeOzi2-0aONmvj4lOggXQ
      short-id: bb3272fa8fc7bdd3
    client-fingerprint: random
    
  - name: "(赠送)日本CN2 GIA专线娱乐节点"
    type: vless
    server: 151.242.164.131
    port: 443
    uuid: 258D0695-F324-4F3F-AF2C-50841AE63315
    network: tcp
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: gateway.icloud.com
    reality-opts:
      public-key: noKW5AewoT8xlv0kdC5zc7EU9xQyBejvkTLCyYeUBjw
      short-id: 2144fd4211f37e7d
    client-fingerprint: random

  - name: "(赠送)韩国CN2专线娱乐节点"
    type: vless
    server: 61.111.247.22
    port: 443
    uuid: 258D0695-F324-4F3F-AF2C-50841AE63315
    network: tcp
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: gateway.icloud.com
    reality-opts:
      public-key: F6Asg31ihdkFCmTdIuGjq_232PMYhLsCH9k3Npaa9VI
      short-id: 0d9954fe36197887
    client-fingerprint: random
    
  - name: "(赠送)日本CN2专线娱乐节点"
    type: vless
    server: 103.232.213.30
    port: 443
    uuid: 258D0695-F324-4F3F-AF2C-50841AE63315
    network: tcp
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: gateway.icloud.com
    reality-opts:
      public-key: 5xYLyky8PE34VoJkoL3PmTUS0Mtmp36fOSYB_52E4EM
      short-id: bac09a67ddb49ee5
    client-fingerprint: random
    
  - name: "(赠送)美国CN2专线娱乐节点"
    type: vless
    server: 38.150.1.87
    port: 443
    uuid: 258D0695-F324-4F3F-AF2C-50841AE63315
    network: tcp
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: gateway.icloud.com
    reality-opts:
      public-key: -RAMGBKwXprvtfSffDSueYpBPHXCDRnt_R2zSggmOxQ
      short-id: e998042224c98bce
    client-fingerprint: random
    
  - name: "(赠送)美国CN22专线娱乐节点"
    type: vless
    server: 38.150.1.149
    port: 443
    uuid: 258D0695-F324-4F3F-AF2C-50841AE63315
    network: tcp
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: gateway.icloud.com
    reality-opts:
      public-key: 8i7j9_b2KyQC8iR-jEMGl-d2whPkeKt36mutUkZr9ng
      short-id: 3477a74403cf4af9
    client-fingerprint: random
    

proxy-groups:
  - name: "EqualVPN"
    type: select
    proxies:
      - "专属纯净静态住宅节点"
      - "(赠送)美国CN2 GIA专线娱乐节点"
      - "(赠送)香港CN2专线娱乐节点(不计入总流量)"
      - "(赠送)香港CN22专线娱乐节点(不计入总流量)"
      - "(赠送)日本CN2 GIA专线娱乐节点"
      - "(赠送)韩国CN2专线娱乐节点"
      - "(赠送)日本CN2专线娱乐节点"
      - "(赠送)美国CN2专线娱乐节点"
      - "(赠送)美国CN22专线娱乐节点"
      - "DIRECT"

rules:
  - GEOSITE,category-ads-all,REJECT
  - GEOIP,PRIVATE,DIRECT,no-resolve
  - DOMAIN-SUFFIX,browserleaks.com,EqualVPN
  - DOMAIN-SUFFIX,ipleak.net,EqualVPN
  - DOMAIN-SUFFIX,dnsleaktest.com,EqualVPN
  - DST-PORT,25,DIRECT
  - DST-PORT,110,DIRECT
  - DST-PORT,143,DIRECT
  - DST-PORT,465,DIRECT
  - DST-PORT,587,DIRECT
  - DST-PORT,993,DIRECT
  - DST-PORT,995,DIRECT
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  - DOMAIN-SUFFIX,bilivideo.com,DIRECT
  - DOMAIN-SUFFIX,douyu.com,DIRECT
  - DOMAIN-SUFFIX,douyucdn.cn,DIRECT
  - DOMAIN-SUFFIX,gov.cn,DIRECT
  - DOMAIN-SUFFIX,gov,DIRECT
  - GEOSITE,GOOGLE,EqualVPN
  - GEOSITE,YOUTUBE,EqualVPN
  - GEOSITE,TELEGRAM,EqualVPN
  - GEOSITE,NETFLIX,EqualVPN
  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,EqualVPN